sudo: true
language: cpp
compiler: gcc
dist: trusty


before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

addons: 
  apt: 
    sources: 
        - ubuntu-toolchain-r-test 
    packages: 
        - lcov

install: 
  # C++17
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo pip install codecov

os:
  - linux

compiler:
  - g++

script:

  - sudo apt-get -qq update
  - sudo apt-get install -y libgtest-dev valgrind cmake
  - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
  - sudo tar xf release-1.7.0.tar.gz
  - cd googletest-release-1.7.0
  - sudo cmake -DBUILD_SHARED_LIBS=ON .
  - sudo make
  - sudo cp -a include/gtest /usr/include
  - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
  - cd ..
  - mkdir build
  - cd build/
    #- g++ -std=c++0x ../src/*.cpp -o main
  - g++ -std=c++14 ../src/*.cpp -o main
    #- g++ ../tests/test_main.cpp -lgtest -lpthread -o main-ut
    #- g++ -o main-ut ../tests/test_main.cpp /usr/lib/libgtest.so /usr/lib/libgtest_main.so -lgtest -lpthread  
  - g++ -std=c++14 -o main-ut ../tests/test_main.cpp -lgtest -lpthread ../src/Printer.cpp ../src/HighestLowest.cpp ../tests/PrinterTest.cpp ../tests/HighestLowestTest.cpp
  - ./main
  - ./main-ut
